<?php

return [
    [
        'key'         => 'launch',
        'name'        => 'Launch',
        'price'        => 'Rp 49.000/bulan',
        'price_raw'    => 49000,
        'kuota'        => 'Maks. 150 pelanggan',
        'badge'        => null,
        'description'  => 'Cocok untuk ISP baru. Billing dasar & fitur standard.',
        'benefits'     => [
            'Invoice otomatis',
            'Portal pelanggan',
            'Pembayaran QRIS & transfer manual',
            'Laporan pelanggan & pembayaran',
        ],
        'highlight'    => false,
        'cta'         => 'https://wa.me/6281287282084',
        'cta_label'   => 'Daftar Sekarang',
        'is_enterprise' => false,
        'icon_key'    => 'rocket',
    ],
    [
        'key'         => 'growth',
        'name'        => 'Growth',
        'price'        => 'Rp 74.000/bulan',
        'price_raw'    => 74000,
        'kuota'        => 'Maks. 350 pelanggan',
        'badge'        => 'PALING POPULER',
        'description'  => 'Untuk ISP yang mulai berkembang. Multi-tenant + bonus reporting.',
        'benefits'     => [
            'Semua di paket Launch',
            'Pembayaran online Midtrans',
            'Virtual account & e-wallet',
            'Laporan arus kas per area',
            'Data pelanggan lebih banyak',
        ],
        'highlight'    => true,
        'cta'         => 'https://wa.me/6281287282084',
        'cta_label'   => 'Daftar Sekarang',
        'is_enterprise' => false,
        'icon_key'    => 'chart',
    ],
    [
        'key'         => 'professional',
        'name'        => 'Pro',
        'price'        => 'Rp 119.000/bulan',
        'price_raw'    => 119000,
        'kuota'        => 'Maks. 750 pelanggan',
        'badge'        => null,
        'description'  => 'Untuk ISP dengan banyak pelanggan. Payment gateway premium & SLA prioritasi.',
        'benefits'     => [
            'Semua di paket Growth',
            'Laporan lebih lengkap',
            'SLA prioritas',
            'Rest API access',
        ],
        'highlight'    => false,
        'cta'         => 'https://wa.me/6281287282084',
        'cta_label'   => 'Daftar Sekarang',
        'is_enterprise' => false,
        'icon_key'    => 'monitor',
    ],
    [
        'key'         => 'biz',
        'name'        => 'Biz',
        'price'        => 'Rp 199.000/bulan',
        'price_raw'    => 199000,
        'kuota'        => 'Maks. 1.500 pelanggan',
        'badge'        => null,
        'description'  => 'Untuk ISP skala menengah-besar. Dedicated support & fitur lengkap.',
        'benefits'     => [
            'Semua di paket Pro',
            'Dedicated support 24/7',
            'Multi-cabang & multi-tim',
            'Custom laporan',
        ],
        'highlight'    => false,
        'cta'         => 'https://wa.me/6281287282084',
        'cta_label'   => 'Daftar Sekarang',
        'is_enterprise' => false,
        'icon_key'    => 'trending',
    ],
    [
        'key'         => 'ultra',
        'name'        => 'Ultra',
        'price'        => 'Rp 399.000/bulan',
        'price_raw'    => 399000,
        'kuota'        => 'Maks. 3.000 pelanggan',
        'badge'        => null,
        'description'  => 'Untuk ISP berskala besar. Performa tinggi & custom integration.',
        'benefits'     => [
            'Semua di paket Biz',
            'Performa tinggi',
            'Custom integration',
            'Priority SLA',
        ],
        'highlight'    => false,
        'cta'         => 'https://wa.me/6281287282084',
        'cta_label'   => 'Daftar Sekarang',
        'is_enterprise' => false,
        'icon_key'    => 'globe',
    ],
    [
        'key'         => 'enterprise',
        'name'        => 'Enterprise / Kustom',
        'price'        => 'Hubungi Kami',
        'price_raw'    => null,
        'kuota'        => 'Kuota tak terbatas',
        'badge'        => null,
        'description'  => 'Butuh lebih dari paket tertinggi? Tim kami bantu rancang solusi kustom.',
        'benefits'     => [
            'Semua fitur paket Ultra',
            'Custom everything',
            'Dedicated account manager',
            'On-site training (opsional)',
            'SLA enterprise-level',
        ],
        'highlight'    => false,
        'cta'         => 'https://wa.me/6281287282084',
        'cta_label'   => 'Hubungi Sales',
        'is_enterprise' => true,
        'icon_key'    => 'building',
    ],
];